# Generated by Django 4.2.1 on 2024-03-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='токен'),
        ),
    ]
